
CREATE USER 'rootSpotify'@'localhost' IDENTIFIED BY 'rootSpotify';
GRANT USAGE ON *.* TO 'rootSpotify'@'localhost';
FLUSH PRIVILEGES;
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `spotify`.* TO 'rootSpotify'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;